server:
  port: 8080
  servlet:
    context-path: /api/v1/gestao
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://yoeswazhacshyv:2962976325d0bf6d171901b64fafbc46a0636f0d5a07a664806c4d22587f7655@ec2-35-169-188-58.compute-1.amazonaws.com:5432/d4fukhk0gardla
    username: yoeswazhacshyv
    password: 2962976325d0bf6d171901b64fafbc46a0636f0d5a07a664806c4d22587f7655
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none 
